### ISSUE TITLE
Delay on scrollThere seems to raise an error

### ISSUE THREAD

**Issue by anlek** [rightjs/rightjs-core#11]
When running `$("posts").scrollThere.delay(1000);` I get (via chrome console):

``` javascript
Uncaught TypeError: Object function (options) {
    this.win().scrollTo(this, options);
    return this;
  } has no method 'win'
Element.include.scrollThereright-src.js:3246
Function.include.bind
```

I thought it was because I was using CoffeeScript but I tried it right in the console and got the same issue.

I might be using it wrong, I also tried calling `$("posts").highlight.delay(1000);` and I get this error:

``` javascript
Uncaught TypeError: Cannot read property 'style' of undefined
Fx.Highlight.Class.prepare
Class_Methods.include.$A.filter.each.Object.each
Fx.RightJS.Fx.Class.start
call_fx
Element.include.highlight
Function.include.bind
```

Thanks in advance.

**Comment by anlek** [comment]
The only way around this I found was this:

``` javascript
var func = function(){
  $('posts').scrollThere();
}
func.delay(500);
```

**Comment by kaievns** [comment]
that's because `highlight` is just an anonymous function, you need to bind it in the context of your element before you call `delay`. Say like that

```
var element = $('posts');
element.highlight.bind(element).delay(500);
```

Check also this article, if you haven't seen it before http://rightjs.org/tutorials/functional-programming

**Comment by anlek** [comment]
You're so correct, that did work!
