### ISSUE TITLE
Jammit don't play well with RightJS and Rails.js together

### ISSUE THREAD

**Issue by anlek** [rightjs/rightjs-core#13]
I have a script that is trying to change the RR settings. Everything works great on development (in rails) but when I go into staging/production, the javascript has an error "RR is not defined". Not sure why.

**Comment by kaievns** [comment]
Probably because `right-rails` automatically switches between `rails-src.js` and `rails.js` depending on the environment. You might want to save your changes in both of the files

**Comment by anlek** [comment]
But I'm not using the right-rails function to include the assets, I'm calling rails.js directly and getting it compressed with Jammit.

**Comment by kaievns** [comment]
That's probably not a rightjs issue then. But why would you need to compress already compressed files? Are you trying to patch the `rails.js` file itself? If you need to adjust the `RR.Options` you should do that in your `application.js` file

**Comment by anlek** [comment]
I'm actually trying to combine right.js, rails.js and application.js into one file. I actually turned off compression thinking that might be the issue. It just seems that when they're in one file (even without the application.js) I get this RR not defined issue. 

I'll try to look a bit closer at the issue and report back.

**Comment by cjk** [comment]
I'm having trouble when compressing right-src.js too:

Since I'm on Rails 3.1, the asset-pipeline compresses (using uglifier) all JS by default. But this breaks IE8 in production. IE8 hangs and throws errors when it encounters uglified rightjs-src.
All is fine in development or even with minified rightjs.js.

Looks like RightJS + Uglifier (used by Sprockets) don't play along each other.

**Comment by kaievns** [comment]
@cjk I think you need to add both `right.js` and `right-olds.js` into your `application.js` file

**Comment by cjk** [comment]
Yep, that was it (again). Once I cloned the right-js source and build a module including olds-support, all was working again. Uff.

**Comment by kaievns** [comment]
@cjk 

You don't have to do that, you can just include both in your application.js file

``` javascript
/**
 * = require right.js
 * = require right-olds.js
 * = require right/stuff.js
 */
```
