### ISSUE TITLE
Error in Google Chrome on receiving json

### ISSUE THREAD

**Issue by Paxa** [rightjs/rightjs-core#2]
If I run in chrome console this code it fires error "SyntaxError: Unexpected token :"

```
{"a": 1231} 
```

When I receive json from server it fires error on $eval(this.text);

```
tryScripts: function(response) {
  var content_type = this.getHeader('Content-type');

  if (this.evalResponse || (this.evalJS && /(ecma|java)script/i.test(content_type))) {
    $eval(this.text);
  } else if (/json/.test(content_type) && this.evalJSON) {
    this.json = this.responseJSON = this.sanitizedJSON();
  } else if (this.evalScripts) {
    this.text.evalScripts();
  }
},
```

http://github.com/rightjs/rightjs-core/blob/master/src/xhr/xhr.js line 235

So there is no way to skip $eval(this.text); in response has js-headers

I think that line should looks like (&& instead ||)

```
if (this.evalResponse && (this.evalJS && /(ecma|java)script/i.test(content_type))) {
```

Or may be I think in wrong way ?

**Comment by kaievns** [comment]
no, I believe it should be like it is.

It seems like your server sends the `javascript` content-type, so Xhr tries to treat it as a piece of javascript and evals it. If you send JSON data, you should specify the `json` content-type on your server, then Xhr will convert it into a json data and assign the `responseJSON` property

**Comment by Paxa** [comment]
Thank you, but is the way to skip this $eval(this.text); ?

**Comment by kaievns** [comment]
можно указать опцию `evalJS` в `false` и потом вручную собрать JSON, как-то вот так

```
Xhr.load('/boo/hoo', {
  evalJS: false,
  onSuccess: function() {
    var json_data = this.sanitizedJSON();
  }
});
```

**Comment by Paxa** [comment]
It helps, it's really right way to send json

**Comment by kaievns** [comment]
don't know, I kinda like it with headers, you specify the `application/json` content type and have all the data checked and prepared for you automatically.

PS будут вопросы приходи в ирку на #rightjs я там каждый день
