### ISSUE TITLE
$$(element).on(...)

### ISSUE THREAD

**Issue by lucassmagal** [rightjs/rightjs-core#20]
Hello,

I'm testing RightJS now to put it in a new project, so I'm still learning the API. A little question: Firebug says that this is not correct:

```
<p>P 1</p>
<p>P 2</p>
<p>P 3</p>

$$('p').on('click', function() {
    console.log('clicked');
});
```

The result: "$$('p').on is not a function". How can I bind a event to a set of elements? Only "p".on(...) will work?

**Comment by kaievns** [comment]
`$$` returns an array, so you can use the `Array#each` method to loop through every item on the list and assign events manually, or use the events delegation features http://rightjs.org/tutorials/events-delegation.

ps. please ask questions at the google group
